import type { Meta, StoryObj } from '@storybook/react-vite';

import { tokens, type EmbrToken } from '../../tokens/generated/tokens';

/**
 * The swatches are generated from the *same* typed export the library ships — not from a
 * hand-written list. Add or rename a semantic token in tokens/ and this story follows it on the
 * next `build:tokens`; delete one and the build fails. The docs cannot drift from the pipeline.
 */
const colorTokensUnder = (role: string): EmbrToken[] =>
  Object.values(tokens).filter((token) => token.type === 'color' && token.path[0] === role);

const GROUPS = [
  {
    role: 'bg',
    title: 'Background',
    description: 'Page, raised surfaces, and the subtle fill used for hover and table zebra.',
  },
  {
    role: 'text',
    title: 'Text',
    description: 'Default body copy, muted secondary copy, and text that sits on a brand fill.',
  },
  {
    role: 'border',
    title: 'Border',
    description: 'Dividers and component outlines.',
  },
  {
    role: 'brand',
    title: 'Brand',
    description:
      'Embr’s identity: the primary action colour, its stronger variant, the accent and links.',
  },
  {
    role: 'focus',
    title: 'Focus',
    description: 'The focus ring. Every interactive component must show it — see golden rule 2.',
  },
  {
    role: 'status',
    title: 'Status',
    description:
      'Deliberately generic. Embr is domain-agnostic, so it ships neutral/info/success/warning/danger and never a business meaning. The consuming app maps them to its own states.',
  },
] as const;

function Swatch({ token }: { token: EmbrToken }) {
  return (
    <div className="flex items-center gap-3">
      <div
        // The chip is decorative — the name and value next to it carry the information — so it
        // is hidden from assistive tech rather than given a redundant label.
        aria-hidden="true"
        className="size-8 shrink-0 rounded-md border border-border"
        style={{ backgroundColor: `var(${token.cssVar})` }}
      />
      <div className="min-w-0">
        <div className="truncate font-medium text-ink">{token.name}</div>
        <code className="block truncate text-sm text-ink-muted">{token.cssVar}</code>
      </div>
    </div>
  );
}

function Group({
  title,
  description,
  swatches,
}: {
  title: string;
  description: string;
  swatches: EmbrToken[];
}) {
  return (
    <section className="flex flex-col gap-4 rounded-lg border border-border bg-surface p-5 shadow-sm">
      <header className="flex flex-col gap-1">
        <h2 className="font-heading text-xl font-semibold text-ink">{title}</h2>
        <p className="max-w-prose text-sm text-ink-muted">{description}</p>
      </header>
      <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">
        {swatches.map((token) => (
          <Swatch key={token.name} token={token} />
        ))}
      </div>
    </section>
  );
}

function SemanticColors() {
  return (
    <div className="flex min-h-screen flex-col gap-6 bg-page p-6 font-body">
      <header className="flex flex-col gap-2">
        <h1 className="font-heading text-3xl font-bold text-ink">Semantic colors</h1>
        <p className="max-w-prose text-ink-muted">
          Components consume these roles, never the raw palette. Each swatch reads its colour from
          the CSS custom property generated by Style Dictionary, so switching the theme in the
          toolbar re-resolves every one of them without a single component re-render.
        </p>
      </header>
      {GROUPS.map((group) => (
        <Group
          key={group.role}
          title={group.title}
          description={group.description}
          swatches={colorTokensUnder(group.role)}
        />
      ))}
    </div>
  );
}

const meta = {
  title: 'Foundations/Colors',
  component: SemanticColors,
  parameters: {
    docs: {
      description: {
        component:
          'The semantic colour layer: the only colours a component is allowed to reference. ' +
          'Primitives (the raw palette) sit underneath and are an implementation detail.',
      },
    },
  },
  tags: ['autodocs'],
} satisfies Meta<typeof SemanticColors>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Semantic: Story = {};

/** The same tokens under the dark token mode — no component changes, only the values behind them. */
export const Dark: Story = {
  globals: { theme: 'dark' },
};
