/**
 * Assembles the three CSS entry points that Embr publishes.
 *
 *   dist/tokens.css   the raw custom properties, light + dark. Framework-agnostic: usable
 *                     without Tailwind at all.
 *   dist/preset.css   tokens.css + the Tailwind @theme layer. The normal entry point.
 *   dist/styles.css   preset.css + Embr's opinionated base layer.
 *
 * Vite's library mode only emits CSS that is imported from JavaScript, and Embr deliberately
 * never does that (see `sideEffects: false` in package.json), so the CSS is assembled here
 * instead. `.storybook/storybook.css` composes the same layers in the same order for dev.
 */
import { mkdir, readFile, writeFile } from 'node:fs/promises';

const GENERATED = 'src/tokens/generated';
const SRC = 'src/css';
const DIST = 'dist';

const BANNER = `/*! Embr — generated by \`npm run build\`. Do not edit. */\n`;

const read = (path) => readFile(path, 'utf8');

await mkdir(DIST, { recursive: true });

const [light, dark, theme, base] = await Promise.all([
  read(`${GENERATED}/tokens.css`),
  read(`${GENERATED}/tokens.dark.css`),
  read(`${SRC}/theme.css`),
  read(`${SRC}/base.css`),
]);

// Custom properties only — no Tailwind required.
await writeFile(`${DIST}/tokens.css`, `${BANNER}${light}\n${dark}`);

// The Tailwind entry. `@import` must precede every other rule, hence the leading line.
await writeFile(`${DIST}/preset.css`, `${BANNER}@import './tokens.css';\n\n${theme}`);

// Everything, plus base element styles.
await writeFile(`${DIST}/styles.css`, `${BANNER}@import './preset.css';\n\n${base}`);

console.log('✔︎ dist/tokens.css\n✔︎ dist/preset.css\n✔︎ dist/styles.css');
