/**
 * Style Dictionary v5 — the single source of truth for every design value in Embr.
 *
 *   tokens/*.json (DTCG)  ──▶  src/tokens/generated/tokens.css       :root                    (light)
 *                         ──▶  src/tokens/generated/tokens.dark.css  :root[data-theme=dark]  (dark)
 *                         ──▶  src/tokens/generated/tokens.ts        typed export
 *
 * Run with `npm run build:tokens`. Every dev/build/test script regenerates it first, so the
 * output can never drift from the tokens.
 */
import StyleDictionary from 'style-dictionary';

const PREFIX = 'embr';
const BASE_FONT_SIZE = 16;
const OUT = 'src/tokens/generated/';

/** Semantic roles. Everything under these paths is theme-able; primitives are not. */
const SEMANTIC_ROOTS = new Set(['bg', 'text', 'border', 'brand', 'focus', 'status']);
const isSemantic = (token) => SEMANTIC_ROOTS.has(token.path[0]);

/** SD keeps the original DTCG key and the transformed one; prefer whichever is present. */
const valueOf = (token) => token.$value ?? token.value;

/**
 * px → rem, so type and spacing scale with the user's browser font size (a11y).
 * `radius.full` is excluded on purpose: it is a "pill" sentinel, not a measurement, and
 * 9999px reads better than 624.9375rem in the generated CSS.
 */
StyleDictionary.registerTransform({
  name: 'embr/dimension-rem',
  type: 'value',
  transitive: true,
  filter: (token) => {
    const isPill = token.path[0] === 'radius' && token.path[1] === 'full';
    return token.$type === 'dimension' && !isPill;
  },
  transform: (token) => {
    const px = parseFloat(valueOf(token));
    return px === 0 ? '0' : `${px / BASE_FONT_SIZE}rem`;
  },
});

/**
 * A typed TS export — not `Record<string, string>`. Consumers (and our own stories) get
 * autocompletion over token names and a compile error when one is renamed or removed.
 */
StyleDictionary.registerFormat({
  name: 'embr/typescript-tokens',
  format: ({ dictionary }) => {
    const entries = dictionary.allTokens.map((token) => {
      const key = token.name.replace(new RegExp(`^${PREFIX}-`), '');
      const fields = [
        `    name: '${key}'`,
        `    cssVar: '--${token.name}'`,
        `    value: ${JSON.stringify(String(valueOf(token)))}`,
        `    type: '${token.$type}'`,
        `    path: [${token.path.map((p) => `'${p}'`).join(', ')}]`,
      ];
      const description = token.$description ?? token.description;
      if (description) fields.push(`    description: ${JSON.stringify(description)}`);
      return `  '${key}': {\n${fields.join(',\n')},\n  },`;
    });

    return `// Generated by \`npm run build:tokens\` from tokens/. Do not edit.
/* eslint-disable */

export interface EmbrToken {
  /** Token name, kebab-cased and un-prefixed — e.g. \`brand-primary\`. */
  readonly name: string;
  /** The CSS custom property this token compiles to — e.g. \`--${PREFIX}-brand-primary\`. */
  readonly cssVar: string;
  /** Resolved value in the light theme. */
  readonly value: string;
  /** DTCG \`$type\` — \`color\`, \`dimension\`, \`fontFamily\`, \`fontWeight\`, \`shadow\`. */
  readonly type: string;
  /** Path through the token tree — e.g. \`['brand', 'primary']\`. */
  readonly path: readonly string[];
  readonly description?: string;
}

export const tokens = {
${entries.join('\n')}
} as const satisfies Record<string, EmbrToken>;

export type TokenName = keyof typeof tokens;

/**
 * Reference a token from inline styles or custom CSS.
 * Prefer the Tailwind utilities from \`preset.css\`; reach for this when you cannot.
 */
export function cssVar(name: TokenName): string {
  return \`var(\${tokens[name].cssVar})\`;
}
`;
  },
});

/** Shared CSS transform pipeline: SD's `css` group, with our rem transform swapped in. */
const cssTransforms = [
  ...StyleDictionary.hooks.transformGroups.css.filter((t) => t !== 'size/rem'),
  'embr/dimension-rem',
];

/** @returns {import('style-dictionary/types').Config} */
const cssPlatform = (destination, selector, filter) => ({
  transforms: cssTransforms,
  prefix: PREFIX,
  files: [
    {
      destination,
      format: 'css/variables',
      filter,
      options: { selector, outputReferences: true },
    },
  ],
});

async function buildAll() {
  // Light: the full token set — primitives, semantics and core — on :root.
  const light = new StyleDictionary({
    source: ['tokens/*.json'],
    platforms: {
      css: { buildPath: OUT, ...cssPlatform('tokens.css', ':root') },
      ts: {
        transforms: cssTransforms,
        prefix: PREFIX,
        buildPath: OUT,
        files: [{ destination: 'tokens.ts', format: 'embr/typescript-tokens' }],
      },
    },
  });

  // Dark: `include` is the base layer, `source` the overrides on top. Using include/source
  // (rather than two `source` entries) is what tells Style Dictionary this is an intentional
  // override and not a token collision.
  //
  // Only the semantic layer is emitted: primitives are theme-independent and already live on
  // :root from the light build. That means the `var(--embr-color-*)` references in this file
  // point at declarations in tokens.css — valid at runtime, but SD can't verify across files,
  // so it warns. The warning is the only one this build can produce, and it's a false positive.
  const dark = new StyleDictionary({
    include: ['tokens/*.json'],
    source: ['tokens/themes/dark/*.json'],
    log: { warnings: 'disabled' },
    platforms: {
      css: {
        buildPath: OUT,
        ...cssPlatform('tokens.dark.css', ":root[data-theme='dark']", isSemantic),
      },
    },
  });

  await light.hasInitialized;
  await light.buildAllPlatforms();

  await dark.hasInitialized;
  await dark.buildAllPlatforms();
}

await buildAll();
